######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/favicon.svg"
logo_on_black: "/favicon_dark.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
### 1200 × 600 ###
images: ["/social.webp"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: false

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: ""
  instagram: "https://www.instagram.com/uoaeronautics"
  landscape: ""
  linkedin: "https://www.linkedin.com/company/uoaeronautics/"
  mastodon: ""
  pinterest: ""
  rss: "https://aeronautics.uottawa.xyz/blog/index.xml"
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false

