######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/UOA-w.png"
logo_on_black: "/img/UOA-b.png"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
### 1200 × 600 ###
images: ["/img/plane1.jpg"]

github:
  repo_url: "https://github.com/username/repo/blob/master"
  show_edit_link: false

social_links:
  devstats: ""
  discord: "https://we-are-jammin.xyz/"
  facebook: ""
  flickr: ""
  github: ""
  instagram: "https://we-are-jammin.xyz/"
  landscape: ""
  linkedin: ""
  mastodon: "https://we-are-jammin.xyz/"
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: "https://we-are-jammin.xyz/"

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false

email: uoat@uottawa.xyz
address: 1234 Clown Avenue, Ottawa, Ontario, Canada
